apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: packetcaptureconfigs.networking.packet.io
spec:
  group: networking.packet.io
  names:
    kind: PacketCaptureConfig
    plural: packetcaptureconfigs
    singular: packetcaptureconfig
    shortNames:
      - pcc
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
      - name: Status
        type: string
        jsonPath: .status.phase
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              anyOf:
                - required: ["targetIPs"]
                - required: ["podSelector"]
              properties:
                targetIPs:
                  type: array
                  items:
                    type: string
                    pattern: '^(\d{1,3}\.){3}\d{1,3}$'
                  description: "IP addresses to capture"
                podSelector:
                  type: object
                  description: "Pod-based capture configuration"
                  properties:
                    pods:
                      type: array
                      description: "List of pods to capture traffic for"
                      items:
                        type: object
                        properties:
                          podName:
                            type: string
                            description: "Name of the pod"
                          namespace:
                            type: string
                            description: "Namespace of the pod (defaults to current namespace)"
                        required:
                          - podName
                  required:
                    - pods
                targetPorts:
                  type: array
                  items:
                    type: integer
                    minimum: 1
                    maximum: 65535
                duration:
                  type: integer
                  description: "Duration in seconds for the packet capture"
                  default: 60
                  minimum: 1
                maxPackets:
                  type: integer
                  description: "Maximum number of packets to capture"
                  default: 1000
                  minimum: 1
                outputFormat:
                  type: string
                  enum: ["pcap", "text", "stdout"]
                  default: "pcap"
                filter:
                  type: string
                  description: "Additional tcpdump filter expression"
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Starting", "Running", "Completed", "Failed"]
                message:
                  type: string
                lastUpdateTime:
                  type: string
                  format: date-time
                captureResults:
                  type: object
                  additionalProperties:
                    type: object
                captureFiles:
                  type: object
                  description: "Paths to captured files on each node"
                  additionalProperties:
                    type: object
                    properties:
                      status:
                        type: string
                      output_file:
                        type: string
                      file_size:
                        type: integer
          required:
            - spec