apiVersion: v1
kind: ConfigMap
metadata:
  name: packet-capture-config
  namespace: kube-system
data:
  # Maximum number of capture files to keep per node (default: 5)
  MAX_CAPTURE_FILES: "5"
  
  # Maximum size of each capture file in MB (default: 10)
  MAX_CAPTURE_FILE_SIZE_MB: "10"
  
  # Log level for controller (DEBUG, INFO, WARNING, ERROR)
  LOG_LEVEL: "INFO"
  
  # Agent port (default: 8080)
  AGENT_PORT: "8080"