apiVersion: v1
kind: ServiceAccount
metadata:
  name: packet-capture-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packet-capture-controller
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["networking.packet.io"]
  resources: ["packetcaptureconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.packet.io"]
  resources: ["packetcaptureconfigs/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packet-capture-controller
subjects:
- kind: ServiceAccount
  name: packet-capture-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: packet-capture-controller
  apiGroup: rbac.authorization.k8s.io